# Generated by Django 3.1.4 on 2020-12-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='deaadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
